### ISSUE TITLE
Spots MVP

### ISSUE THREAD

**Issue by cscov** [cscov/StarWarsBnb#10]
**A spot is a location that a user can reserve.** 
- [x] Users can browse all spots on the spots index page
     - [x]  Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] Users can view info about a specific spot on the spot show page
    - [x]  Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature
 - [x] Users cannot add a spot or update a spot listing.
    - [x]  Adequate styling
    - [x] Smooth, bug-free navigation
    - [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by cscov** [comment]
accidentally assigned you before I had pushed the latest version to heroku. fixed!

**Comment by xnanodax** [comment]
Great work :) The core functionality is there. I am closing this issue.

If you happen to come back to this project, I would reduce the spacing between the pic and the spot title.

![screen shot 2018-04-13 at 3 14 22 pm](https://user-images.githubusercontent.com/20424731/38759972-783185e8-3f2d-11e8-8e67-2a9387b3c8d2.png)

Because when I look into the show page, I see a picture but no text below unless I scroll. It makes it look like the page is only partially done but you have spent so much time getting this show page to work.

AirBnB
![screen shot 2018-04-13 at 3 16 05 pm](https://user-images.githubusercontent.com/20424731/38760002-b57db070-3f2d-11e8-9672-dc5081b167b3.png)

StarwarsBnB
![screen shot 2018-04-13 at 3 16 09 pm](https://user-images.githubusercontent.com/20424731/38760005-b7f06316-3f2d-11e8-859c-c3d5ef261be5.png)

**Comment by cscov** [comment]
thanks, fixed!
